# Generated by Django 4.0.3 on 2022-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='shop/img/')),
                ('text_title', models.CharField(max_length=200)),
                ('event_text', models.TextField()),
            ],
        ),
    ]
