# Generated by Django 4.0.3 on 2022-03-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукции'},
        ),
    ]
