# Generated by Django 4.0.3 on 2022-03-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentcharacteristics',
            options={'verbose_name': 'Характеристику квартиры', 'verbose_name_plural': 'Характеристики квартиры'},
        ),
        migrations.AddField(
            model_name='apartmentcharacteristics',
            name='what_apartment',
            field=models.CharField(default='1-ая квартира', max_length=300),
        ),
    ]
